# Generated by Django 3.1.3 on 2020-11-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
